import type { Flight, MatchResult, Winery } from './types';

const weekdayHours = (open: string, close: string) => ({
  monday: { open, close },
  tuesday: { open, close },
  wednesday: { open, close },
  thursday: { open, close },
  friday: { open, close },
  saturday: { open, close },
  sunday: { open, close },
});

const standardHours = weekdayHours('10:00', '17:00');

const dryCreekFlights: Flight[] = [
  {
    id: 'dcv-classic',
    wineryId: 'dry-creek-vineyard',
    name: 'Classic Tasting',
    price: 25,
    durationMinutes: 45,
    winesIncluded: 5,
    format: 'standing',
    hasFoodPairing: false,
    description: 'Five estate wines including our flagship Dry Creek Valley Zinfandel.',
  },
  {
    id: 'dcv-picnic',
    wineryId: 'dry-creek-vineyard',
    name: 'Picnic & Pour',
    price: 35,
    durationMinutes: 60,
    winesIncluded: 4,
    format: 'picnic',
    hasFoodPairing: true,
    description: 'Four wines paired with a seasonal cheese board on the picnic grounds.',
  },
  {
    id: 'dcv-reserve',
    wineryId: 'dry-creek-vineyard',
    name: 'Reserve Flight',
    price: 55,
    durationMinutes: 60,
    winesIncluded: 4,
    format: 'seated',
    hasFoodPairing: false,
    description: 'Four single-vineyard and reserve selections in a seated setting.',
  },
];

const williamsSelyemFlights: Flight[] = [
  {
    id: 'ws-estate',
    wineryId: 'williams-selyem',
    name: 'Estate Tasting',
    price: 85,
    durationMinutes: 60,
    winesIncluded: 5,
    format: 'seated',
    hasFoodPairing: false,
    description: 'Five current releases including estate Pinot Noirs and Chardonnays.',
  },
  {
    id: 'ws-library',
    wineryId: 'williams-selyem',
    name: 'Library & Reserve',
    price: 150,
    durationMinutes: 90,
    winesIncluded: 6,
    format: 'seated',
    hasFoodPairing: true,
    description: 'Six wines spanning library vintages paired with artisan provisions.',
  },
];

const jordanFlights: Flight[] = [
  {
    id: 'jordan-estate',
    wineryId: 'jordan-winery',
    name: 'Estate Tour & Tasting',
    price: 65,
    durationMinutes: 90,
    winesIncluded: 4,
    format: 'seated',
    hasFoodPairing: true,
    description: 'Guided estate tour with four wines paired with bites from the estate kitchen.',
  },
  {
    id: 'jordan-seasonal',
    wineryId: 'jordan-winery',
    name: 'Seasonal Lunch',
    price: 190,
    durationMinutes: 120,
    winesIncluded: 5,
    format: 'seated',
    hasFoodPairing: true,
    description:
      'Multi-course seasonal lunch on the terrace paired with current and library wines.',
  },
];

const ironHorseFlights: Flight[] = [
  {
    id: 'ih-bubbles',
    wineryId: 'iron-horse-vineyards',
    name: 'Bubble Bar',
    price: 40,
    durationMinutes: 45,
    winesIncluded: 4,
    format: 'outdoor',
    hasFoodPairing: false,
    description: 'Four sparkling wines served outdoors with panoramic Green Valley views.',
  },
  {
    id: 'ih-reserve',
    wineryId: 'iron-horse-vineyards',
    name: 'Joy! Reserve Experience',
    price: 75,
    durationMinutes: 60,
    winesIncluded: 5,
    format: 'seated',
    hasFoodPairing: true,
    description: 'Five sparkling and still wines with seasonal pairings in the salon.',
  },
];

const gundlachBundschuFlights: Flight[] = [
  {
    id: 'gb-heritage',
    wineryId: 'gundlach-bundschu',
    name: 'Heritage Tasting',
    price: 30,
    durationMinutes: 45,
    winesIncluded: 5,
    format: 'standing',
    hasFoodPairing: false,
    description: 'Five wines spanning our 160-year history in the Rhinefarm tasting room.',
  },
  {
    id: 'gb-cave',
    wineryId: 'gundlach-bundschu',
    name: 'Cave Tasting',
    price: 55,
    durationMinutes: 60,
    winesIncluded: 4,
    format: 'seated',
    hasFoodPairing: true,
    description: 'Four wines tasted inside the historic cave with small bites.',
  },
  {
    id: 'gb-outdoor',
    wineryId: 'gundlach-bundschu',
    name: 'Hillside Picnic',
    price: 45,
    durationMinutes: 60,
    winesIncluded: 3,
    format: 'picnic',
    hasFoodPairing: true,
    description: 'Three wines with a picnic basket on the hillside overlooking the valley.',
  },
];

const ramseyFlights: Flight[] = [
  {
    id: 'ram-intro',
    wineryId: 'ramsey-cellars',
    name: 'Introduction Tasting',
    price: 20,
    durationMinutes: 30,
    winesIncluded: 4,
    format: 'standing',
    hasFoodPairing: false,
    description: 'Four approachable wines from our Dry Creek vineyards.',
  },
  {
    id: 'ram-family',
    wineryId: 'ramsey-cellars',
    name: 'Family Reserve',
    price: 35,
    durationMinutes: 45,
    winesIncluded: 5,
    format: 'standing',
    hasFoodPairing: false,
    description: 'Five wines including our single-vineyard Zinfandel.',
  },
];

const scribeFlights: Flight[] = [
  {
    id: 'scribe-hacienda',
    wineryId: 'scribe-winery',
    name: 'Hacienda Tasting',
    price: 65,
    durationMinutes: 75,
    winesIncluded: 4,
    format: 'seated',
    hasFoodPairing: true,
    description: 'Four wines with a seasonal mezze plate at the historic Hacienda.',
  },
  {
    id: 'scribe-cellar',
    wineryId: 'scribe-winery',
    name: 'Cellar Tasting',
    price: 95,
    durationMinutes: 90,
    winesIncluded: 5,
    format: 'seated',
    hasFoodPairing: true,
    description: 'Seated cellar tasting with five wines and a full food pairing.',
  },
];

const silverOakFlights: Flight[] = [
  {
    id: 'so-current',
    wineryId: 'silver-oak',
    name: 'Current Release',
    price: 50,
    durationMinutes: 45,
    winesIncluded: 3,
    format: 'seated',
    hasFoodPairing: false,
    description: 'Three current-vintage Cabernet Sauvignons from both estates.',
  },
  {
    id: 'so-library',
    wineryId: 'silver-oak',
    name: 'Library Tasting',
    price: 120,
    durationMinutes: 75,
    winesIncluded: 4,
    format: 'seated',
    hasFoodPairing: true,
    description: "Four library vintages with artisan cheese in the Bonny's Vineyard Room.",
  },
];

export const mockWineries: Winery[] = [
  {
    id: 'dry-creek-vineyard',
    slug: 'dry-creek-vineyard',
    name: 'Dry Creek Vineyard',
    tagline: 'The birthplace of Dry Creek Valley Zinfandel',
    story:
      'Founded in 1972 as the first new winery in Dry Creek Valley after Prohibition, Dry Creek Vineyard helped define Sonoma Zinfandel. The tasting room opens onto shaded picnic grounds bordered by ancient oaks. Dogs are welcome, walk-ins are the norm, and flights start at $25 — making it one of the most accessible stops in the region.',
    region: 'Dry Creek Valley',
    city: 'Healdsburg',
    latitude: 38.6529,
    longitude: -122.9395,
    hours: standardHours,
    setting: 'vineyard',
    reservationType: 'walk_ins_welcome',
    bookingUrl: 'https://www.drycreekvineyard.com/visit',
    groupSizeMax: 8,
    parking: 'Free lot',
    varietals: ['Zinfandel', 'Sauvignon Blanc', 'Cabernet Sauvignon'],
    signatureVarietals: ['Zinfandel'],
    vibes: ['Relaxed & Scenic', 'Social & Lively'],
    noiseLevel: 'moderate',
    styleScores: {
      styleRelaxed: 4,
      styleAdventurous: 2,
      styleEducational: 2,
      styleCelebratory: 3,
      styleSocial: 4,
    },
    minFlightPrice: 25,
    maxFlightPrice: 55,
    flights: dryCreekFlights,
    isDogFriendly: true,
    isKidFriendly: true,
    isWheelchairAccessible: true,
    hasFoodPairing: true,
    hasOutdoorSeating: true,
    hasViews: true,
    isMembersOnly: false,
    averageRating: 4.6,
    ratingsCount: 1240,
    qualityScore: 3,
    popularityScore: 4,
    ratingGoogle: 4.6,
  },
  {
    id: 'williams-selyem',
    slug: 'williams-selyem',
    name: 'Williams Selyem',
    tagline: 'Cult Pinot Noir, by appointment only',
    story:
      "What started as a garage operation in the 1980s became one of California's most coveted Pinot Noir producers. Williams Selyem remains fiercely independent, selling almost exclusively through their mailing list. Visiting the estate on Westside Road is a pilgrimage for Pinot lovers — small groups, unhurried pours, and vineyards that disappear into fog.",
    region: 'Russian River Valley',
    city: 'Healdsburg',
    latitude: 38.5835,
    longitude: -122.9185,
    hours: {
      ...standardHours,
      monday: null,
      tuesday: null,
    },
    setting: 'estate',
    reservationType: 'appointment_only',
    bookingUrl: 'https://www.williamsselyem.com/visit',
    groupSizeMax: 6,
    parking: 'Free lot',
    varietals: ['Pinot Noir', 'Chardonnay'],
    signatureVarietals: ['Pinot Noir'],
    vibes: ['Educational', 'Relaxed & Scenic'],
    noiseLevel: 'quiet',
    styleScores: {
      styleRelaxed: 4,
      styleAdventurous: 2,
      styleEducational: 5,
      styleCelebratory: 2,
      styleSocial: 1,
    },
    minFlightPrice: 85,
    maxFlightPrice: 150,
    flights: williamsSelyemFlights,
    isDogFriendly: false,
    isKidFriendly: false,
    isWheelchairAccessible: true,
    hasFoodPairing: true,
    hasOutdoorSeating: false,
    hasViews: true,
    isMembersOnly: false,
    averageRating: 4.9,
    ratingsCount: 680,
    qualityScore: 5,
    popularityScore: 4,
    ratingGoogle: 4.9,
  },
  {
    id: 'jordan-winery',
    slug: 'jordan-winery',
    name: 'Jordan Vineyard & Winery',
    tagline: 'A Bordeaux-inspired estate in Alexander Valley',
    story:
      "Modeled after a French château, Jordan's ivy-covered estate sits among 1,200 acres of rolling hills. Everything here is designed around the full-day experience — seasonal lunches on the terrace, vineyard hikes, and pours of their benchmark Cabernet Sauvignon. It's a celebration-worthy destination that earns its premium price.",
    region: 'Alexander Valley',
    city: 'Healdsburg',
    latitude: 38.7127,
    longitude: -122.8948,
    hours: weekdayHours('10:00', '16:30'),
    setting: 'estate',
    reservationType: 'appointment_only',
    bookingUrl: 'https://www.jordanwinery.com/visit',
    groupSizeMax: 12,
    parking: 'Free lot',
    varietals: ['Cabernet Sauvignon', 'Chardonnay'],
    signatureVarietals: ['Cabernet Sauvignon'],
    vibes: ['Celebratory', 'Educational'],
    noiseLevel: 'quiet',
    styleScores: {
      styleRelaxed: 3,
      styleAdventurous: 2,
      styleEducational: 4,
      styleCelebratory: 5,
      styleSocial: 3,
    },
    minFlightPrice: 65,
    maxFlightPrice: 190,
    flights: jordanFlights,
    isDogFriendly: false,
    isKidFriendly: false,
    isWheelchairAccessible: true,
    hasFoodPairing: true,
    hasOutdoorSeating: true,
    hasViews: true,
    isMembersOnly: false,
    averageRating: 4.8,
    ratingsCount: 2150,
    qualityScore: 5,
    popularityScore: 5,
    ratingGoogle: 4.8,
  },
  {
    id: 'iron-horse-vineyards',
    slug: 'iron-horse-vineyards',
    name: 'Iron Horse Vineyards',
    tagline: 'World-class sparkling wine with a view',
    story:
      "Perched on a ridge in Green Valley — the coolest corner of Russian River — Iron Horse has been making sparkling wine since 1979. Their outdoor tasting bar offers one of Sonoma's most photogenic panoramas. No walls, no roof, just bubbles and rolling hills. Five presidents have served Iron Horse at State dinners.",
    region: 'Russian River Valley',
    city: 'Sebastopol',
    latitude: 38.4225,
    longitude: -122.8103,
    hours: weekdayHours('10:00', '16:00'),
    setting: 'hilltop',
    reservationType: 'appointment_only',
    bookingUrl: 'https://www.ironhorsevineyards.com/visit',
    groupSizeMax: 8,
    parking: 'Free lot',
    varietals: ['Sparkling', 'Chardonnay', 'Pinot Noir'],
    signatureVarietals: ['Sparkling'],
    vibes: ['Relaxed & Scenic', 'Celebratory'],
    noiseLevel: 'moderate',
    styleScores: {
      styleRelaxed: 5,
      styleAdventurous: 3,
      styleEducational: 2,
      styleCelebratory: 4,
      styleSocial: 2,
    },
    minFlightPrice: 40,
    maxFlightPrice: 75,
    flights: ironHorseFlights,
    isDogFriendly: false,
    isKidFriendly: true,
    isWheelchairAccessible: false,
    hasFoodPairing: true,
    hasOutdoorSeating: true,
    hasViews: true,
    isMembersOnly: false,
    averageRating: 4.7,
    ratingsCount: 890,
    qualityScore: 4,
    popularityScore: 4,
    ratingGoogle: 4.7,
  },
  {
    id: 'gundlach-bundschu',
    slug: 'gundlach-bundschu',
    name: 'Gundlach Bundschu',
    tagline: "Sonoma's oldest family winery, never boring",
    story:
      "The Bundschu family has been growing grapes on this Rhinefarm property since 1858. Don't let the history fool you — GunBun is irreverent, fun, and welcoming. Dogs roam the grounds, live music fills the amphitheater in summer, and the hiking trails wind through vineyards to hilltop views of the Sonoma Valley. It's the anti-stuffy winery.",
    region: 'Sonoma Valley',
    city: 'Sonoma',
    latitude: 38.2825,
    longitude: -122.3759,
    hours: standardHours,
    setting: 'vineyard',
    reservationType: 'walk_ins_welcome',
    bookingUrl: 'https://www.gunbun.com/visit',
    groupSizeMax: 10,
    parking: 'Free lot',
    varietals: ['Pinot Noir', 'Cabernet Sauvignon', 'Merlot', 'Zinfandel'],
    signatureVarietals: ['Pinot Noir', 'Zinfandel'],
    vibes: ['Social & Lively', 'Adventurous'],
    noiseLevel: 'lively',
    styleScores: {
      styleRelaxed: 2,
      styleAdventurous: 4,
      styleEducational: 2,
      styleCelebratory: 3,
      styleSocial: 5,
    },
    minFlightPrice: 30,
    maxFlightPrice: 55,
    flights: gundlachBundschuFlights,
    isDogFriendly: true,
    isKidFriendly: true,
    isWheelchairAccessible: true,
    hasFoodPairing: true,
    hasOutdoorSeating: true,
    hasViews: true,
    isMembersOnly: false,
    averageRating: 4.7,
    ratingsCount: 1830,
    qualityScore: 4,
    popularityScore: 5,
    ratingGoogle: 4.7,
  },
  {
    id: 'ramsey-cellars',
    slug: 'ramsey-cellars',
    name: 'Ramsey Cellars',
    tagline: 'Small-lot wines, big welcome',
    story:
      "A family-run operation tucked off West Dry Creek Road, Ramsey Cellars focuses on small-lot Zinfandel and Rhône-style blends. The tasting room doubles as the barrel room — pull up a stool, chat with the winemaker, and taste wines you won't find anywhere else. Walk-ins are welcome and flights start at $20, making it one of the best-value stops in wine country.",
    region: 'Dry Creek Valley',
    city: 'Healdsburg',
    latitude: 38.6621,
    longitude: -122.9501,
    hours: {
      monday: null,
      tuesday: null,
      wednesday: { open: '11:00', close: '16:00' },
      thursday: { open: '11:00', close: '16:00' },
      friday: { open: '11:00', close: '17:00' },
      saturday: { open: '11:00', close: '17:00' },
      sunday: { open: '11:00', close: '16:00' },
    },
    setting: 'vineyard',
    reservationType: 'walk_ins_welcome',
    bookingUrl: 'https://www.ramseycellars.com',
    groupSizeMax: 6,
    parking: 'Gravel lot',
    varietals: ['Zinfandel', 'Syrah'],
    signatureVarietals: ['Zinfandel'],
    vibes: ['Relaxed & Scenic', 'Educational'],
    noiseLevel: 'quiet',
    styleScores: {
      styleRelaxed: 5,
      styleAdventurous: 2,
      styleEducational: 4,
      styleCelebratory: 1,
      styleSocial: 2,
    },
    minFlightPrice: 20,
    maxFlightPrice: 35,
    flights: ramseyFlights,
    isDogFriendly: true,
    isKidFriendly: false,
    isWheelchairAccessible: false,
    hasFoodPairing: false,
    hasOutdoorSeating: true,
    hasViews: false,
    isMembersOnly: false,
    averageRating: 4.8,
    ratingsCount: 210,
    qualityScore: 3,
    popularityScore: 2,
    ratingGoogle: 4.8,
  },
  {
    id: 'scribe-winery',
    slug: 'scribe-winery',
    name: 'Scribe Winery',
    tagline: 'Old-world soul, new California energy',
    story:
      'Built around a pre-Prohibition hacienda on the slopes of Sonoma Mountain, Scribe blends California farming with European winemaking instincts. The wines — Riesling, Pinot Noir, Chardonnay, Sylvaner — are unconventional for Sonoma. So is the experience: mezze plates, seasonal menus, and a setting that feels more Mediterranean villa than tasting room. Members-only on weekends, but weekday appointments are open.',
    region: 'Carneros',
    city: 'Sonoma',
    latitude: 38.2665,
    longitude: -122.4192,
    hours: {
      monday: { open: '10:30', close: '17:00' },
      tuesday: { open: '10:30', close: '17:00' },
      wednesday: { open: '10:30', close: '17:00' },
      thursday: { open: '10:30', close: '17:00' },
      friday: { open: '10:30', close: '17:00' },
      saturday: null,
      sunday: null,
    },
    setting: 'estate',
    reservationType: 'reservations_recommended',
    bookingUrl: 'https://www.scribewinery.com/visit',
    groupSizeMax: 4,
    parking: 'Free lot',
    varietals: ['Pinot Noir', 'Chardonnay', 'Rosé'],
    signatureVarietals: ['Pinot Noir'],
    vibes: ['Adventurous', 'Celebratory'],
    noiseLevel: 'moderate',
    styleScores: {
      styleRelaxed: 3,
      styleAdventurous: 5,
      styleEducational: 3,
      styleCelebratory: 4,
      styleSocial: 3,
    },
    minFlightPrice: 65,
    maxFlightPrice: 95,
    flights: scribeFlights,
    isDogFriendly: false,
    isKidFriendly: false,
    isWheelchairAccessible: true,
    hasFoodPairing: true,
    hasOutdoorSeating: true,
    hasViews: true,
    isMembersOnly: false,
    averageRating: 4.5,
    ratingsCount: 1450,
    qualityScore: 4,
    popularityScore: 5,
    ratingGoogle: 4.5,
  },
  {
    id: 'silver-oak',
    slug: 'silver-oak',
    name: 'Silver Oak',
    tagline: 'The Cabernet Sauvignon benchmark',
    story:
      "Silver Oak's Alexander Valley estate is a modernist landmark — LEED Platinum certified, built from reclaimed stone and wine-barrel staves. The winery makes exactly one wine per estate: Cabernet Sauvignon, aged exclusively in American oak. The tasting room is polished and unhurried, the grounds immaculate. It's the kind of place you bring someone to impress.",
    region: 'Alexander Valley',
    city: 'Geyserville',
    latitude: 38.7285,
    longitude: -122.8712,
    hours: weekdayHours('10:00', '17:00'),
    setting: 'estate',
    reservationType: 'appointment_only',
    bookingUrl: 'https://www.silveroak.com/visit/alexander-valley',
    groupSizeMax: 10,
    parking: 'Free lot',
    varietals: ['Cabernet Sauvignon'],
    signatureVarietals: ['Cabernet Sauvignon'],
    vibes: ['Celebratory', 'Educational'],
    noiseLevel: 'quiet',
    styleScores: {
      styleRelaxed: 3,
      styleAdventurous: 1,
      styleEducational: 4,
      styleCelebratory: 5,
      styleSocial: 2,
    },
    minFlightPrice: 50,
    maxFlightPrice: 120,
    flights: silverOakFlights,
    isDogFriendly: false,
    isKidFriendly: false,
    isWheelchairAccessible: true,
    hasFoodPairing: true,
    hasOutdoorSeating: true,
    hasViews: true,
    isMembersOnly: false,
    averageRating: 4.7,
    ratingsCount: 3200,
    qualityScore: 5,
    popularityScore: 5,
    ratingGoogle: 4.7,
  },
];

export const mockResultsCasualCouple: MatchResult[] = [
  {
    winery: mockWineries[0], // Dry Creek Vineyard
    rank: 1,
    score: 96,
    matchReasons: [
      'Perfect for Zinfandel lovers',
      'Walk-in friendly — no reservation needed',
      'Picnic grounds and outdoor seating',
    ],
  },
  {
    winery: mockWineries[4], // Gundlach Bundschu
    rank: 2,
    score: 91,
    matchReasons: [
      'Dog-friendly with scenic hiking trails',
      'Great value flights from $30',
      'Walk-in welcome, no appointment needed',
    ],
  },
  {
    winery: mockWineries[3], // Iron Horse
    rank: 3,
    score: 87,
    matchReasons: [
      'Best sparkling wine views in Sonoma',
      'Outdoor tasting with panoramic hillside views',
      'Mid-range pricing from $40',
    ],
  },
  {
    winery: mockWineries[5], // Ramsey Cellars
    rank: 4,
    score: 82,
    matchReasons: [
      'Most affordable flights in the region',
      'Meet the winemaker in the barrel room',
      'Relaxed, intimate setting',
    ],
  },
  {
    winery: mockWineries[6], // Scribe
    rank: 5,
    score: 74,
    matchReasons: [
      "Unique varietals you won't find elsewhere",
      'Beautiful hacienda setting',
      'Food pairings included with every flight',
    ],
  },
];

export const mockResultsLuxuryGroup: MatchResult[] = [
  {
    winery: mockWineries[2], // Jordan
    rank: 1,
    score: 98,
    matchReasons: [
      'Château-style estate perfect for celebrations',
      'Multi-course seasonal lunch available',
      'Accommodates groups up to 12',
    ],
  },
  {
    winery: mockWineries[7], // Silver Oak
    rank: 2,
    score: 94,
    matchReasons: [
      'Benchmark Cabernet Sauvignon',
      'Stunning LEED Platinum architecture',
      'Polished, impressive setting',
    ],
  },
  {
    winery: mockWineries[1], // Williams Selyem
    rank: 3,
    score: 89,
    matchReasons: [
      'Cult Pinot Noir — bucket-list winery',
      'Intimate, unhurried experience',
      'Library vintages available',
    ],
  },
  {
    winery: mockWineries[6], // Scribe
    rank: 4,
    score: 83,
    matchReasons: [
      'Mediterranean-inspired setting',
      'Adventurous wine selection',
      'Full food pairings at every level',
    ],
  },
  {
    winery: mockWineries[3], // Iron Horse
    rank: 5,
    score: 78,
    matchReasons: [
      'Sparkling wine served at State dinners',
      'Outdoor tasting with best views in Sonoma',
      'Celebratory atmosphere',
    ],
  },
];
