/**
 * Type system overview:
 *
 * DATABASE TYPES (generated):
 *   `src/lib/database.types.ts` — auto-generated by `pnpm db:gen-types`.
 *   Never hand-edit. Contains row types for every Supabase table, enum types,
 *   and insert/update helpers. Re-generate after every migration change.
 *
 * APP TYPES (this file):
 *   Hand-maintained types for the quiz, scoring engine, and UI display layers.
 *   These re-export DB enums for convenience and define shapes that don't map
 *   1:1 to a database row (QuizAnswers, MatchResult, WineryForMatching, etc.).
 *
 * When the generated types exist, DB row types (Tables['wineries']['Row'], etc.)
 * are the source of truth for data shape. The app types below provide the
 * domain-specific projections consumed by the scoring engine and UI.
 */

// ---------------------------------------------------------------------------
// Enums — mirror the Postgres enums from migration 001.
// Once database.types.ts is generated, these can be replaced with:
//   import type { Database } from './database.types';
//   type ReservationType = Database['public']['Enums']['reservation_type'];
// For now, keep them inline so the app compiles without a running DB.
// ---------------------------------------------------------------------------

export type ReservationType =
  | 'walk_ins_welcome'
  | 'reservations_recommended'
  | 'appointment_only';

export type NoiseLevel = 'quiet' | 'moderate' | 'lively';

export type FlightFormat =
  | 'seated'
  | 'standing'
  | 'tour'
  | 'outdoor'
  | 'picnic'
  | 'bar';

export type AvaRegion =
  | 'russian_river_valley'
  | 'dry_creek_valley'
  | 'alexander_valley'
  | 'sonoma_valley'
  | 'carneros'
  | 'sonoma_coast'
  | 'sonoma_mountain'
  | 'green_valley'
  | 'petaluma_gap'
  | 'rockpile';

export type Setting = 'vineyard' | 'estate' | 'downtown' | 'hilltop' | 'cave';

/**
 * @deprecated Use AvaRegion instead. Kept for backward compatibility with
 * existing UI code that references the display-friendly region names.
 */
export type Region =
  | 'Russian River Valley'
  | 'Dry Creek Valley'
  | 'Sonoma Valley'
  | 'Alexander Valley'
  | 'Carneros'
  | 'Sonoma Coast';

export type BudgetBand = '$' | '$$' | '$$$' | '$$$$';

export type Vibe =
  | 'Relaxed & Scenic'
  | 'Educational'
  | 'Celebratory'
  | 'Adventurous'
  | 'Social & Lively';

export type Varietal =
  | 'Pinot Noir'
  | 'Chardonnay'
  | 'Cabernet Sauvignon'
  | 'Zinfandel'
  | 'Sparkling'
  | 'Rosé'
  | 'Sauvignon Blanc'
  | 'Merlot'
  | 'Syrah';

// ---------------------------------------------------------------------------
// Hours
// ---------------------------------------------------------------------------

export type DayHours = {
  open: string;
  close: string;
} | null;

export type WeeklyHours = {
  monday: DayHours;
  tuesday: DayHours;
  wednesday: DayHours;
  thursday: DayHours;
  friday: DayHours;
  saturday: DayHours;
  sunday: DayHours;
};

// ---------------------------------------------------------------------------
// Style scores — app-layer names used by the scoring engine and mock data.
// The DB stores these as style_classic, style_luxury, style_family_friendly,
// style_social, style_sustainable, style_adventure. The mapper layer
// (future src/lib/mappers.ts) converts between DB rows and these names.
//
// Mapping from SCORING.md vibe dimensions to CSV/DB style columns:
//   styleRelaxed     -> style_classic (calm, traditional experiences)
//   styleAdventurous -> style_adventure
//   styleEducational -> style_sustainable (overlaps with eco/process focus)
//   styleCelebratory -> style_luxury
//   styleSocial      -> style_social
//   (style_family_friendly is used for kid/family hard filters, not vibe scoring)
// ---------------------------------------------------------------------------

export type StyleScores = {
  styleRelaxed: number;
  styleAdventurous: number;
  styleEducational: number;
  styleCelebratory: number;
  styleSocial: number;
};

/**
 * DB-aligned style scores matching the wineries table columns exactly.
 * Used by the mapper layer when reading from / writing to the database.
 */
export type DbStyleScores = {
  style_classic: number;
  style_luxury: number;
  style_family_friendly: number;
  style_social: number;
  style_sustainable: number;
  style_adventure: number;
};

// ---------------------------------------------------------------------------
// Flight — display type used by UI components.
// ---------------------------------------------------------------------------

export type Flight = {
  id: string;
  wineryId: string;
  name: string;
  price: number;
  durationMinutes: number;
  winesIncluded: number;
  format: FlightFormat;
  hasFoodPairing: boolean;
  description: string;
};

// ---------------------------------------------------------------------------
// Winery — full shape for detail pages and data layer.
// ---------------------------------------------------------------------------

export type Winery = {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  story: string;
  region: Region;
  city: string;
  latitude: number;
  longitude: number;
  setting: Setting | null;
  hours: WeeklyHours;
  reservationType: ReservationType;
  bookingUrl: string;
  groupSizeMax: number | null;
  parking: string;
  varietals: Varietal[];
  signatureVarietals: Varietal[];
  vibes: Vibe[];
  noiseLevel: NoiseLevel;
  styleScores: StyleScores;
  minFlightPrice: number;
  maxFlightPrice: number;
  flights: Flight[];
  isDogFriendly: boolean;
  isKidFriendly: boolean;
  isWheelchairAccessible: boolean;
  hasFoodPairing: boolean;
  hasOutdoorSeating: boolean;
  hasViews: boolean;
  isMembersOnly: boolean;
  averageRating: number | null;
  ratingsCount: number | null;
  qualityScore: number | null;
  popularityScore: number | null;
  ratingGoogle: number | null;
};

// ---------------------------------------------------------------------------
// Quiz / matching — app-only types (no direct DB table).
// ---------------------------------------------------------------------------

export type MustHaves = {
  views: boolean;
  foodPairing: boolean;
  outdoorSeating: boolean;
  dogFriendly: boolean;
  kidFriendly: boolean;
  wheelchairAccessible: boolean;
};

export type QuizAnswers = {
  selectedVarietals: Varietal[];
  selectedVibes: Vibe[];
  budgetBand: BudgetBand | null;
  mustHaves: MustHaves;
  preferredRegions: Region[];
  numStops: number;
  includeMembersOnly: boolean;
  groupSize: number | null;
};

export type MatchResult = {
  winery: Winery;
  rank: number;
  score: number;
  matchReasons: string[];
};

/**
 * Pre-joined, flat shape consumed by the scoring engine.
 * All fields needed for hard filters + soft scoring in one object --
 * no extra DB queries inside the scoring loop.
 */
export type WineryForMatching = {
  id: string;
  slug: string;
  region: Region;
  reservationType: ReservationType;
  isMembersOnly: boolean;
  groupSizeMax: number | null;

  varietals: Varietal[];

  minFlightPrice: number | null;

  isDogFriendly: boolean;
  isKidFriendly: boolean;
  isWheelchairAccessible: boolean;
  hasFoodPairing: boolean;
  hasOutdoorSeating: boolean;
  hasViews: boolean;

  styleScores: StyleScores;

  qualityScore: number | null;
  popularityScore: number | null;
  ratingGoogle: number | null;
};

/**
 * Everything the UI needs to render a winery across all pages
 * (cards, detail, plan stops, map markers).
 */
export type WineryForDisplay = {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  story: string;
  region: Region;
  city: string;
  latitude: number;
  longitude: number;
  setting: Setting | null;
  hours: WeeklyHours;
  reservationType: ReservationType;
  bookingUrl: string;
  groupSizeMax: number | null;
  parking: string;
  noiseLevel: NoiseLevel;
  varietals: Varietal[];
  signatureVarietals: Varietal[];
  minFlightPrice: number;
  maxFlightPrice: number;
  flights: Flight[];
  averageRating: number | null;
  ratingsCount: number | null;

  isDogFriendly: boolean;
  isKidFriendly: boolean;
  isWheelchairAccessible: boolean;
  hasFoodPairing: boolean;
  hasOutdoorSeating: boolean;
  hasViews: boolean;
  isMembersOnly: boolean;
};

// ---------------------------------------------------------------------------
// Region mapping helpers — convert between DB enum and display string.
// ---------------------------------------------------------------------------

export const AVA_TO_DISPLAY: Record<AvaRegion, Region | string> = {
  russian_river_valley: 'Russian River Valley',
  dry_creek_valley: 'Dry Creek Valley',
  alexander_valley: 'Alexander Valley',
  sonoma_valley: 'Sonoma Valley',
  carneros: 'Carneros',
  sonoma_coast: 'Sonoma Coast',
  sonoma_mountain: 'Sonoma Mountain',
  green_valley: 'Green Valley',
  petaluma_gap: 'Petaluma Gap',
  rockpile: 'Rockpile',
};

export const DISPLAY_TO_AVA: Record<string, AvaRegion> = Object.fromEntries(
  Object.entries(AVA_TO_DISPLAY).map(([k, v]) => [v, k as AvaRegion]),
) as Record<string, AvaRegion>;

// ---------------------------------------------------------------------------
// Reservation type mapping — CSV value to DB enum.
// Used by the import pipeline.
// ---------------------------------------------------------------------------

export const CSV_RESERVATION_MAP: Record<string, ReservationType> = {
  'walk-in-friendly': 'walk_ins_welcome',
  recommended: 'reservations_recommended',
  required: 'appointment_only',
};
